name: "RELEASE_APEX_CONTRIBUTIONS_ADBD"
value: {
  string_value: "adbd.google.contributions.prebuilt"
}
namespace: "android_UNKNOWN"
description: "The contributions made by apexes (source or prebuilts) to the rest of the build."
workflow: MANUAL
containers: "product"
containers: "system"
containers: "system_ext"
containers: "vendor"
