name: "RELEASE_APEX_CONTRIBUTIONS_BLUETOOTH"
value: {
  string_value: "bluetooth.google.contributions.prebuilt"
}
namespace: "android_UNKNOWN"
description: ""
workflow: MANUAL
containers: "product"
containers: "system"
containers: "system_ext"
containers: "vendor"
